#!/usr/bin/python

import os
import re
import Image
import imghdr
import argparse

DATE_TIME_ORIGINAL_TAG = 0x9003

def get_date_time_original(file_name):
    i = Image.open(file_name)
    info = i._getexif()
    return info[DATE_TIME_ORIGINAL_TAG]

def list_files(path, recursive):
    files = []
    for dirpath, dirs, filenames in os.walk(path):
        for f in filenames:
            full = os.path.join(dirpath, f)
            files.append(full)
        if not recursive: 
            break
    return files

def is_image(f):
    return os.path.isfile(f) and imghdr.what(f) in ['jpeg', 'gif', 'png']

def new_name(file_path):
    dirname = os.path.dirname(file_path)
    name = get_date_time_original(file_path).replace(' ', '_').replace(':', '.')
    ext = os.path.splitext(file_path)[1].lower()
    return os.path.join(dirname, "%s.0%s" % (name,ext))
    
def color(text, color):
    cmap = {'red': '0;31', 'green':'0;32'}
    return "\33["+cmap[color]+"m"+text+"\33[0m"

def print_change(old, new):
    print os.path.dirname(os.path.commonprefix((old, new)))
    print ' ', color(os.path.basename(old), 'red'), '->',
    print color(os.path.basename(new), 'green')

def remove_duplicates(pairs):
    return filter(lambda (x, y): x!=y, pairs)

def bump_name(path):
    def inc(m):
        return m.group(1) + str(int(m.group(2))+1) + m.group(3)
    return re.sub("(.*\.+)([\d]+)(\..*)$", inc, path)

def ensure_uniqueness(names):
    if not names:
        return []
    is_used = lambda name: os.path.exists(name) or name in unique_names
    old, new = zip(*names)
    unique_names = []
    for name in new:
        while is_used(name):
            name = bump_name(name)
        unique_names.append(name)
    return zip(old, unique_names)

def rename(pair):
    old, new = pair
    if os.path.exists(new):
        print "WARN: file already exists! Could not rename:"
    else:
        os.rename(old, new)
    print_change(old, new)

if __name__=='__main__':
    parser = argparse.ArgumentParser(description='Rename image files based on the EXIF OriginalTime field.')
    parser.add_argument('-r', '--recursive', help='enable recursive renaming in subdirectories', action='store_true')
    parser.add_argument('-d', '--directory', help='directory of files to rename (defaults to .)', default='.')
    args = parser.parse_args()

    files = list_files(args.directory, args.recursive)
    images = filter(is_image, files)
    old_names = map(os.path.abspath, images)
    if old_names:
        new_names = map(new_name, old_names)
        pairs = zip(old_names, new_names)
        pairs = remove_duplicates(pairs)
        pairs = ensure_uniqueness(pairs)
        map(rename, pairs)

