#!/usr/bin/python

import os
import Image
import imghdr
import argparse

DATE_TIME_ORIGINAL_TAG = 0x9003

def get_date_time_original(file_name):
    i = Image.open(file_name)
    info = i._getexif()
    return info[DATE_TIME_ORIGINAL_TAG]

def list_files(path, recursive):
    files = []
    for dirpath, dirs, filenames in os.walk(path):
        for f in filenames:
            full = os.path.join(dirpath, f)
            files.append(full)
        if not recursive:
            for d in dirs: dirs.pop()
    return files

def list_image_files(path, recursive):
    return [f for f in list_files(path, recursive) if is_image(f)]

def is_image(f):
    return os.path.isfile(f) and imghdr.what(f) in ['jpeg', 'gif', 'png']

def time_as_filename(t):
    return t.replace(' ', '_').replace(':', '.')

def get_new_name(file_name):
    _, ext = os.path.splitext(file_name)
    t = get_date_time_original(file_name)
    new_name = time_as_filename(t)
    return new_name + ext.lower()

def rename(files):
    for old_path in files:
        path, old_name = os.path.split(old_path)
        new_name = get_new_name(old_path)
        if old_name == new_name: 
            continue
        if os.path.exists(new_name):
            print "WARN: could not rename '%s' to '%s' (already exists)" % (old_name, new_name)
        else:
            new_path = os.path.join(path, new_name)
            print "-", old_path
            print "+", new_path
            os.rename(old_path, new_path)

if __name__=='__main__':
    parser = argparse.ArgumentParser(description="Rename image files based on the EXIF OriginalTime field.")
    parser.add_argument('-r', '--recursive', help='rename subdirectories recursively', action='store_true')
    parser.add_argument('-d', '--directory', help='directory of files to rename (defaults to .)', default='.')
    args = parser.parse_args()

    files = list_image_files(args.directory, args.recursive)
    rename(files)

